### ISSUE TITLE
move all multiline commands to single line

### ISSUE THREAD

**Issue by hguerrero** [RedHat-Middleware-Workshops/dayinthelife-streaming#40]
to avoid the problem with the solution explorer multi-line copy we need to update all those commands to single line commands.

**Comment by dgutride** [comment]
@hguerrero  - is there an open issue against solution explorer for this?

**Comment by hguerrero** [comment]
@dgutride is actually opened against patternfly: https://github.com/patternfly/patternfly/issues/3272

**Comment by dgutride** [comment]
ok, well - that's a little bit embarrassing given it's a project I'm directly involved with...  I'll be back in touch :)

**Comment by hguerrero** [comment]
fixed by using our own fork of solution explorer : https://github.com/redhat-cop/agnosticd/pull/3779
