### ISSUE TITLE
Che link seems broken

### ISSUE THREAD

**Issue by jgholt** [RedHat-Middleware-Workshops/dayinthelife-streaming#79]
When clicking on the code ready containers link I get a new browser tab with the link http://che-che.%7Bopenshift-app-host%7D/.  does not seem like the desired behavior. 

This is the line 

To get started go to the Codeready console and log in using your username and password credentials.
![Screen Shot 2021-03-03 at 2 47 22 PM](https://user-images.githubusercontent.com/44275081/109863214-5d90a600-7c2f-11eb-9e50-787cfacda6b8.png)

**Comment by jgholt** [comment]
figured out the workflow, but it is not very clear from the RHPDS provisioining instructions./

**Comment by hguerrero** [comment]
@jgholt did you try to access from the github repo? Or from the solution explorer?

**Comment by jgholt** [comment]
From the Github repo directly,  I figured it out, although the Directions in the Provisioning Email from RHPDS could use a little clarity.  The Solution Exporter was also off a little telling me to use admin as my user name, instead of user 1.
