### ISSUE TITLE
Erros in Lab2. 

### ISSUE THREAD

**Issue by weimeilin79** [RedHat-Middleware-Workshops/dayinthelife-streaming#80]
Reported by Marc,

We're about to run a module 2 of the DIL streaming workshop for one of our clients here in ANZ and I wanted to alert you to an issue.
When we provision a 1 user training environment (and the bug might be localized to this) we get the error below when the user attempts to rsh to the sqlserver pod
The issue is that the pod-exec ClusterRole never gets created.  I suspect it has something to do with this late [January change ](https://github.com/redhat-cop/agnosticd/pull/3300/files)to this file ([provision_userprojects.yaml](https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-dil-streaming/tasks/provision_userprojects.yaml)) in agnosticd.  Given the nature of the change it's possible this issue only appears for training environments. 

Error is (when trying the oc rsh option)

```
oc rsh mssql-server-linux-58685677bd-xzhr6
Error from server (Forbidden): pods "mssql-server-linux-58685677bd-xzhr6" is forbidden: User "user1" cannot create resource "pods/exec" in API group "" in the namespace "shared-db-earth": RBAC: clusterrole.rbac.authorization.k8s.io "pod-exec" not found
```

**Comment by hguerrero** [comment]
closed by https://github.com/redhat-cop/agnosticd/pull/3524
