### ISSUE TITLE
Integration platform status "Phase: duplicate"

### ISSUE THREAD

**Issue by takleung** [RedHat-Middleware-Workshops/dayinthelife-streaming#86]
Try to deploy the two camel service, Integration platform status error

sh-4.4$ oc -n user2 apply -f $CHE_PROJECTS_ROOT/FleurDeLune/support/projects/module-1/eda-services.yaml
integrationplatform.camel.apache.org/camel-k created
integration.camel.apache.org/inventory-events created
integration.camel.apache.org/invoice-events created

Expected status: Ready

**Comment by hguerrero** [comment]
fixed by https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/commit/0b9753529de8aa919c7ce04cc989a079940a6b99

**Comment by hguerrero** [comment]
fixed by https://github.com/RedHat-Middleware-Workshops/dayinthelife-streaming/commit/0b9753529de8aa919c7ce04cc989a079940a6b99
